// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtZpIBN6VmtI4c72V9HVSH1DsuTQsOmRU',
    appId: '1:1067668686991:android:87a2796ed205c7b5b548fa',
    messagingSenderId: '1067668686991',
    projectId: 'maseerah-2',
    storageBucket: 'maseerah-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcfDtXuyMegtyIcWFusECCQRVgnOP2tM',
    appId: '1:1067668686991:ios:4a6e53dc08bc43aab548fa',
    messagingSenderId: '1067668686991',
    projectId: 'maseerah-2',
    storageBucket: 'maseerah-2.firebasestorage.app',
    iosBundleId: 'com.example.maseerahApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihlIbCdx7ywIrmPFJ123-ak4ftb6bPQ4',
    appId: '1:1067668686991:web:08eab422fdb1b74fb548fa',
    messagingSenderId: '1067668686991',
    projectId: 'maseerah-2',
    authDomain: 'maseerah-2.firebaseapp.com',
    storageBucket: 'maseerah-2.firebasestorage.app',
    measurementId: 'G-VR2TB136CX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlcfDtXuyMegtyIcWFusECCQRVgnOP2tM',
    appId: '1:1067668686991:ios:4a6e53dc08bc43aab548fa',
    messagingSenderId: '1067668686991',
    projectId: 'maseerah-2',
    storageBucket: 'maseerah-2.firebasestorage.app',
    iosBundleId: 'com.example.maseerahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihlIbCdx7ywIrmPFJ123-ak4ftb6bPQ4',
    appId: '1:1067668686991:web:f4b4394d427e4964b548fa',
    messagingSenderId: '1067668686991',
    projectId: 'maseerah-2',
    authDomain: 'maseerah-2.firebaseapp.com',
    storageBucket: 'maseerah-2.firebasestorage.app',
    measurementId: 'G-RCBY6RFRCB',
  );

}